### PR TITLE
Implement Instance auction type when creates a new listing

### PR DESCRIPTION
**Pull request by prandev01**
Screen Shot 2021-12-27 at 12 20 05 AM

### CODE REVIEW

**Comment by ryanprice** [comment]
Can we update the labels to

Auction Expires
Now (keep the switch here) Future

image

**Comment by prandev01** [comment]
Yes, of course. I can!

**Comment by ryanprice** [comment]
and one last change. Can you default to Future.
and when you slide to Now, can you hide the date picker.
Slide to Future, show the date picker

**Review by ryanprice — APPROVED** [review]
tested changing to expire now and posted a listing

**Pull request merged**
