### PR TITLE
Switchchain button

### PR DESCRIPTION
**Pull request by mchigit**
We prob need better icon images for the different networks. Both moonbeam and moonbase alpha are square shaped icons.

image

image

### CODE REVIEW

**Review by Mikechoi78 — COMMENTED** [review]
I can't look the menus on the top.

**Comment by ryanprice** [comment]
Lets, have the network chooser like https://app.sushi.com/en/swap  top nav for example

more info here
https://github.com/ryanprice/nft-market/issues/186

**Review by ryanprice — APPROVED** [review]
LGTM

**Comment by Mikechoi78** [comment]
I got the compile error.

./src/assets/scss/App.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/assets/scss/App.scss)
Cannot find module 'sass'

**Pull request merged**
